- name: Clone Ubuntu VM on VMware
  hosts: localhost
  gather_facts: no

  vars:
    vcenter_hostname: "vcenter.caverna.local"
    vcenter_user: "administrator@vsphere.local"
    vcenter_password: "{{ lookup('env', 'vcenter_password') }}"
    datacenter: "Caverna Cloud"
    cluster: "nuc-compute"
    template_name: "Ubuntu 24.04"
    vm_name: "k3s-node-01"
    network_name: "VLAN10_192.168.10.0"

  tasks:

    - name: Clone VM from template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        state: poweredon
        networks:
          - name: "{{ network_name }}"
            type: dhcp
        wait_for_ip_address: yes
      register: vm_info

    - name: Show IP
      debug:
        msg: "VM IP: {{ vm_info.instance.ipv4 }}"
